seq = int(input('Digite a quantidade desejada da sequencia fibonacci:'))
n1 = 0
n2 = 1
cont = 3
print(f'{n1} -> {n2}', end='')
while cont <= seq:
    n3 = n1 + n2
    print(f' -> {n3}',end='')
    cont += 1
    n1 = n2
    n2 = n3